# Keycloak settings
keycloak:
  realm: spring_boot_tutorial
  auth-server-url: http://0.0.0.0:8083/
  ssl-required: none
  resource: spring_boot_tutorial
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
keycloak-client:
  client-id: spring_boot_tutorial_client
  client-secret: TXkNefUiBStJtdSTeAP74266tMLUneXU
keycloak-config:
  username: admin_user
  password: admin